### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ivandrofly** [nibblesoft/SubDBSharp#2]
- [x] Copy all the member from Client.cs to SubDbClient.
- [x] Move http related member to ApiConnection.
- [ ] Add properties/members to represent an operation like (Download, Search).
